version: '3'
services:
  redis:
    image: redis
    container_name: myredis
    expose:
     - 6379
  mongo:
    image: mongo
    container_name: mymongo
    command: "--smallfiles"
    ports:
      - '27017:27017'
  hub:
    build: ./hub
    container_name: myhub
    ports:
     - "8081:3000"
    links:
     - mongo
    depends_on:
     - mongo
  dashboard:
    build: ./dashboard
    container_name: mydashboard
    ports:
     - "8080:80"
    links:
     - hub
    depends_on:
     - mongo
     - hub
  access-control:
    build: ./access-control
    container_name: myaccesscontrol
    ports:
     - "8082:8080"
    links:
     - redis
    depends_on:
     - redis
